[project]
name = "bridge-dealer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bridgebots>=0.0.12",
    "opencv-python>=4.11.0.86",
    "pytest>=8.3.5",
]
